import Part from '@/components/Parts';
import RootLayouts from '@/layouts/RootLayouts';
import { Col, Row } from 'antd';
import Head from 'next/head';


export function ProductListPage({products}) {
  const style = {
    background: '#0092ff',
    padding: '8px 0',
  };
  return (
    <>
      <Head>
        <title>PC Complier</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 style={{color:'black'}}>
        This is Category Page
      </h1>
      <div className='container mx-auto grid grid-cols-3 gap-4 mt-8'>
             {
            products?.map((part)=> <Part part={part} key={part._id}></Part>)
          }
      </div>
    </>
  );
};

ProductListPage.getLayout = function getLayout(page) {
  return (
    <RootLayouts>{page}</RootLayouts>
  )
}




export default ProductListPage;


ProductListPage.getLayout = function getLayout(page) {
    return (
      <RootLayouts>{page}</RootLayouts>
    )
  }
  
export async function getServerSideProps(context) {
  
    const res = await fetch(`http://localhost:3000/api/parts?category=${context.params.name}`)
    const data = await res.json()
    return {
      props: {
        products:data.result
      },
    }
  }