import Part from '@/components/Parts';
import RootLayouts from '@/layouts/RootLayouts';
import { addComponent } from '@/redux/featured/pc-complier-slice';
import { Button, Col, Row } from 'antd';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { useDispatch } from 'react-redux';


export function ProductListPage({products}) {
  const dispatch = useDispatch()
  const router = useRouter()
  const setProduct = (product) =>{
    dispatch(addComponent({category:router.query.name,product }))
    router.push('/pc-builder')
  }
  return (
    <>
      <Head>
        <title>PC Complier</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 style={{color:'black'}}>
        This is Category Page
      </h1>
      <div className='container mx-auto grid grid-cols-3 gap-4 mt-8'>
             {
            products?.map((product)=> <Part part={product} key={product._id}>
              <Button onClick={()=>setProduct(product)}>
                Select
              </Button>
            </Part>)
          }
      </div>
    </>
  );
};

ProductListPage.getLayout = function getLayout(page) {
  return (
    <RootLayouts>{page}</RootLayouts>
  )
}




export default ProductListPage;


ProductListPage.getLayout = function getLayout(page) {
    return (
      <RootLayouts>{page}</RootLayouts>
    )
  }
  
export async function getServerSideProps(context) {
  
    const res = await fetch(`http://localhost:3000/api/parts?category=${context.params.name.replace('-','/')}`)
    const data = await res.json()
    return {
      props: {
        products:data.result
      },
    }
  }