import Part from '@/components/Parts';
import RootLayouts from '@/layouts/RootLayouts';
import { Col, Row } from 'antd';
import Head from 'next/head';


export default function CategoriesPage({products}) {
  const style = {
    background: '#0092ff',
    padding: '8px 0',
  };
  return (
    <>
      <Head>
        <title>PC Complier</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 style={{color:'black'}}>
        This is Category Page
      </h1>
      <div className='container mx-auto grid grid-cols-3 gap-4 mt-8'>
             {
            products?.map((part)=> <Part part={part} key={part._id}></Part>)
          }
      </div>
    </>
  );
};

CategoriesPage.getLayout = function getLayout(page) {
  return (
    <RootLayouts>{page}</RootLayouts>
  )
}



export async function getStaticPaths() {
  const res = await fetch('http://localhost:3000/api/categories')
  const data = await res.json()

 console.log(data)
  const paths = data.result.map((category) => ({
    params: { category: category.title},
  }))
 
  return {
    paths,
    fallback: false,
  }
}


export async function getStaticProps(context) {
  const res = await fetch(`http://localhost:3000/api/parts?category=${context.params.category}`)
  const products = await res.json()
  
  
  return {
    props: {
      products: products.result,
    },
  }
}