import Part from '@/components/Parts';
import RootLayouts from '@/layouts/RootLayouts';
import Head from 'next/head';
import { useRouter } from 'next/router';


export default function CategoriesPage({products}) {
  const style = {
    background: '#0092ff',
    padding: '8px 0',
  };
  const router = useRouter()
  return (
    <>
      <Head>
        <title>PC Complier</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h2 className='text-center my-8 text-3xl text-gray-700'>
        {router.query.category.replace('-','/')} Category
      </h2>
      <div className='container mx-auto grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 mt-8'>
             {
            products?.map((part)=> <Part part={part} key={part._id}></Part>)
          }
      </div>
    </>
  );
};

CategoriesPage.getLayout = function getLayout(page) {
  return (
    <RootLayouts>{page}</RootLayouts>
  )
}



export async function getStaticPaths() {
  const res = await fetch('https://pc-complier.vercel.app/api/categories')
  const data = await res.json()

 console.log(data)
  const paths = data.result.map((category) => ({
    params: { category: category.title.replace('/','-')},
  }))
 
  return {
    paths,
    fallback: false,
  }
}


export async function getStaticProps(context) {
  const res = await fetch(`https://pc-complier.vercel.app/api/parts?category=${context.params.category.replace('-','/')}`)
  const products = await res.json()
  
  
  return {
    props: {
      products: products.result,
    },
  }
}