import RootLayouts from '@/layouts/RootLayouts';
import Head from 'next/head';


export default function HomePage() {
  return (
    <>
      <Head>
        <title>PC Complier</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 style={{color:'black'}}>
        This is Home Page
      </h1>
    </>
  );
};

HomePage.getLayout = function getLayout(page) {
  return (
    <RootLayouts>{page}</RootLayouts>
  )
}
