import Banner from '@/components/Banner';
import Category from '@/components/Category';
import Part from '@/components/Parts';
import RootLayouts from '@/layouts/RootLayouts';
import Head from 'next/head';


export default function HomePage({parts,categories}) {
  const style = {
    background: '#0092ff',
    padding: '8px 0',
  };
  return (
    <>
      <Head>
        <title>PC Complier</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h2 className='text-center my-8 text-3xl text-gray-700'>
        Feature Products
      </h2>
      <div className='container mx-auto grid grid-cols-14 md:grid-cols-2 lg:grid-cols-3 gap-4 mt-8'>
             {
            parts?.map(({products})=> <Part part={products} key={products._id}></Part>)
          }
      </div>
      <h2 className='text-center my-8 text-3xl text-gray-700'>
        Feature Categories
      </h2>
      <div className='container mx-auto grid grid-cols-14 md:grid-cols-2 lg:grid-cols-3 gap-4 mt-8'>
             {
            categories?.map((category)=> <Category category={category} key={category._id}></Category>)
          }
      </div>
    </>
  );
};

HomePage.getLayout = function getLayout(page) {
  return (
    <RootLayouts>
      <Banner />
      {page}
      </RootLayouts>
  )
}

export async function getStaticProps() {
  const res = await fetch('https://pc-complier.vercel.app/api/parts/featured')
  const parts = await res.json()
  
  const categoriesRes = await fetch('https://pc-complier.vercel.app/api/categories?limit=6')
  const categories = await categoriesRes.json()
  
  
  return {
    props: {
      parts:parts.result,
      categories:categories.result
    },
    revalidate: 30
  }
}