import Part from '@/components/Parts';
import RootLayouts from '@/layouts/RootLayouts';
import { Col, Row } from 'antd';
import Head from 'next/head';


export default function HomePage({parts}) {
  const style = {
    background: '#0092ff',
    padding: '8px 0',
  };
  return (
    <>
      <Head>
        <title>PC Complier</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 style={{color:'black'}}>
        This is Home Page
      </h1>
      <div className='container mx-auto grid grid-cols-3'>
          
             
             {
            parts?.map((part)=> <Col className="gutter-row" span={8} key={part._id}>
               <Part part={part}></Part>
             </Col>)
          }
      </div>
    </>
  );
};

HomePage.getLayout = function getLayout(page) {
  return (
    <RootLayouts>{page}</RootLayouts>
  )
}

export async function getStaticProps() {
  // Call an external API endpoint to get posts.
  // You can use any data fetching library
  const res = await fetch('http://localhost:3000/api/parts')
  const data = await res.json()
  
  console.log(data)
 
  // By returning { props: { posts } }, the Blog component
  // will receive `posts` as a prop at build time
  return {
    props: {
      parts:data.result,
    },
  }
}