import RootLayouts from '@/layouts/RootLayouts';
import React from 'react';

import Head from 'next/head';
import Part from '@/components/Parts';
import { useRouter } from 'next/router';

const ProductsPage = ({products}) => {
    const router = useRouter()
    return (
        <>
      <Head>
        <title>PC Complier</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h2 className='text-center my-8 text-3xl text-gray-700'>
        All Products
      </h2>
      <div className='container mx-auto grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 mt-8'>
             {
            products?.map((product)=> <Part part={product} key={product._id}></Part>)
          }
      </div>
    </>
    );
};

export default ProductsPage;



ProductsPage.getLayout = function getLayout(page) {
    return (
      <RootLayouts>{page}</RootLayouts>
    )
  } 
  
  
  export async function getStaticProps() {
    
    const res = await fetch(`https://pc-complier.vercel.app/api/parts`)
    const data = await res.json()
    return {
      props: {
        products:data.result
      },
      revalidate: 30
    }
  } 